log:
  filename: "stdout"
mysql:
  user: "root"
  password: "5996"
  host: "localhost"
  port: 3306
  dbname: "PGCloudDisk"
jwt:
  jwtSecret: "PGCloudDisk"
localSave:
  root: "D:/tempFiles"
  trash: "D:/tempFiles/trash"
runMode:
  debug: true
